name: Close Issues

on:
  issues:
    types: [opened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: mihomo-party-org/auto-close-isssues

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        API_URL: ${{ secrets.API_URL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: go run main.go