name: Close Issues

on:
  issues:
    types: [opened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: mihomo-party-org/auto-close-isssues

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.POMPURIN404_TOKEN }}
          API_URL: ${{ secrets.OPENAI_BASE_URL }}
          API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go run main.go
