name: Close Issues

on:
  issues:
    types: [opened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Close Issue
        uses: mihomo-party-org/auto-close-issue@main
        with:
          url: ${{ secrets.OPENAI_BASE_URL }}
          key: ${{ secrets.OPENAI_API_KEY }}
          prompt: ${{ vars.OPENAI_SYSTEM_PROMPT }}
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
